before:
  hooks:
    - mkdir -p builddir
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  dir: ./src
  goos:
  - darwin
  - linux
  - freebsd
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 5
  - 6
  - 7
  ignore:
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: ppc64le
    - goos: darwin
      goarch: s390x
    - goos: freebsd
      goarch: ppc64le
    - goos: freebsd
      goarch: s390x
    - goos: freebsd
      goarch: arm
      goarm: 5
  flags:
  - -trimpath
  ldflags:
  - -s -w -X main.build={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: mac
checksum:
  algorithm: sha512
