version: '2'

vars:
    TARGET_FOLDER: build

    SOURCE_FOLDER:
        sh: find . -regex ".*\.go$" | head -n 1 | grep -Po ".*(?=\/)"

    AUTHOR:
        sh: grep -Po "(?<=name\s=\s).*" ~/.gitconfig

    APP_NAME:
        sh: pwd | tr '/' '\n' | tail -1

    ARCH:
        sh: arch

    DATE:
        sh: date

    GIT_COMMIT_NO:
        sh: git rev-list --all --count

    GIT_COMMIT_HASH:
        sh: git rev-parse HEAD

    GOFILES:
        sh: >-
            find . -type f -regex ".*\.go$" \
                | grep -v "_test.go"  \
                | tr '\n' ' '

tasks:
    run:
        go run {{.GOFILES}}

    default:
        cmds:
            - task: build

    build:
        cmds:
            - cmd: >-
                bob -c
                -f '_subversion: {{.GIT_COMMIT_NO}}, Author: {{.AUTHOR}},
                Build date: {{.DATE}}, Git hash: {{.GIT_COMMIT_HASH}}'
            - cmd: >-
                find build/ -mindepth 1 -maxdepth 1 -type d
                | xargs -i cp conf/* '{}'

    test:
        cmds:
            - cmd: go test -cover -bench=. {{.SOURCE_FOLDER}}/*.go

    deploy:
        cp -rpf build/* ${HOME}/tools/arch/mybins/
